name: Helm Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.11.0'

      - name: Add Bitnami Helm repository
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run Helm Lint
        run: helm lint ./express-postgres

      - name: Package Helm Chart
        run: helm package ./express-postgres -d ./packaged-chart

      - name: Create Helm Release
        run: |
          mkdir -p ./release-artifacts
          mv ./packaged-chart/*.tgz ./release-artifacts/
          helm repo index ./release-artifacts --url https://github.com/umar.fd/express-postgres-chart/releases/download/v0.1.0/

      - name: Upload Helm Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: helm-release
          path: ./release-artifacts
